version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=slack_clone
    ports:
      - '5432:5432'
    volumes:
      - data-volume:/var/lib/postgresql/data
volumes:
  data-volume:
